server:
  port: 8080
  #servlet:
    #context-path: /uploadFile
  jsp-servlet:
    init-parameters:
      development: true

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  servlet:
    multipart:
      max-request-size: 2MB #控制请求可以上传文件大小 尽量小于等于文件实际大小
      max-file-size: 4MB #用来控制文件上传大小

  messages:
    basename: i18n.login
  #禁用缓存
  thymeleaf:
    cache: false
